---
title: "Pushing the AR test beyond the limit"
subtitle: "A novel goodness-of-fit test for high-dimensional applications"
author: "Markku Kuismin"
institute: "University of Oulu, Northern Finland Birth Cohorts"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

- I work as a biostatistician at the University of Oulu School of Medicine.

```{r out.width='100%', fig.height=6, eval=require('leaflet'), echo=FALSE}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  setView(25.23685, 62.58855,  zoom = 4.5) %>%
    addMarkers(c(25.5242, 24.9495), c(65.0075, 60.1696), label = c("My workplace", "We are here"))
```

--

- My research interests are (not limited to) high-dimensional statistic, non-parametric methods and statistical tests.

--

- Here I will introduce a novel multivariate test that also works in high-dimensional case.

---

class: center, middle

# Background and motivation

---

# Background and motivation

- All parametric statistical methods built on assumptions about the the distribution of the random variable.

--

- In multivariate applications dealing high-dimensional data assume the population distribution is multivariate normal.

--

  - Gaussian Graphical Models. If not normal `->` strict conditional-independence interpretation becomes weaker.

--

  - High-dimensional linear discriminant analysis. If not normal `->` other methods such as RF or SVMs may be more robust alternatives.

---

# Background and motivation

- $H_0: f = f_0$

--

- For example, $H_0: f\text{ is a multivariate normal distribution.}$

--

- Several test have been proposed (e.g., Kolmogorov–Smirnov, energy test by Székely and Rizzo (2005), a high-dimensional test by Chen, H & Xia (2023) and many others)

--

- Until we have a test that can detect the difference in 100\% power in every single scenario, this is still an open research problem...

---

class: center, middle

# The AR statistic

---

# The AR statistic

- Based on the Accept-Reject (AR) algorithm.

--

$$\rho = \frac{1}{n}\sum_{i=1}^n \text{I}\Bigl(\frac{f_0(X_i)}{Df(X_i)} > U\Bigr).$$

--

- $\rho$ measures how often $X_i$s from a distribution with density $f$ would be accepted as samples from distribution with density $f_0$. 

---

# The AR statistic

- The algorithm was adapted in Kuismin (2026) for statistical inference.

--

- Main idea: compute $\rho$ under null, that is assume that $f_0$ and $f$ are the same distribution (set the normalizing constant $D = 1$).

--

- Instead of generating pseudo random numbers from $f$, compute $\rho$ with respect to the observed data. 

---

# The AR statistic

Technical challenges:

--

- How to determine $f$?

--

`->` Estimate $f$, e.g., using KDE(...)

--

- $\rho$ depends on an external random variable $U$. How to determine a deterministic 

--

`->` Use $E_U(\rho)$ instead.

--

- Denote $\rho(\textbf{X}) = E_U(\rho) = n^{-1}\sum_{1=1}^n \min\left(1, f_0(X_i)/\widehat{f}(X_i)\right)$.

---

# The AR statistic

The statistic has several attractive properties.

--

Direct probabilistic interpretation:

- The AR statistic can be interpreted as an estimated acceptance probability.

- It measures how often observations would be accepted under the hypothesized population distribution. 

--

- Values close to 1 indicate good agreement with the hypothesized distribution.

- Values close to 0 indicate lack of fit and evidence against the model.

--

- Computing interval estimates for $\rho(\textbf{X})$ can be done using simulations or Poisson-Binomial distribution.

---

# The AR statistic

It is a global measure of distributional agreement

--

- It can detect differences in location, covariance, tail behavior, skewness, multimodality, and other shape features.

--

The statistic is connected to *total variation distance*.

- It measures similarity between the true density $f$ and the hypothesized density $f_0$.

---

# Total variation distance

The total variation distance (TVD) between $f(x)$ and $f_0(x)$ is defined as 

$$\|f(x) - f_0(x)\|_{\text{TV}} = \frac{1}{2}\int_{\mathcal{X}}|f(x) - f_0(x)|\, dx.$$
Then, as $n \to \infty$,

$$\rho(\textbf{X}) \xrightarrow{P} 1 - \|f(x) - f_0(x)\|_{\text{TV}}.$$

See Kuismin (2026) for more detailed description and proof.

---

# Challenges 

- The statistic depends on a density estimate $f$.

--

`->` Estimating $f$ is more or less hopeless in high-dimensional setting.

--

- However, let's test how well $\rho(\textbf{X})$ works when making decision whether to reject $H_0$ or not.

---

# References

Chen, H & Xia, Y. (2023). A Normality Test for High-dimensional Data Based on the Nearest Neighbor Approach, Journal of the American Statistical Association,
118, 719-731, https://doi.org/10.1080/01621459.2021.1953507

Kuismin, M. (2025). Using the rejection sampling for finding tests. arXiv preprint arXiv:2509.10325.

Székely, G. J. & Rizzo, M. L. (2005). A new test for multivariate normality. Journal of Multivariate Analysis 93, 58-80, https://doi.org/10.1016/j.jmva.2003.12.002

---

class: center, middle

# Thanks!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

(Something a bit different for Beamer presentations.)
